version: '3.1'
services:
  webserver:
    #container_name: ${APP_NAME}_webserver
    #build:
    #  context: ./web
    container_name: ${APP_NAME}_webserver
    image: mosaicodev/lamborghinicms:0.0.2
    #image: mondonuovo_app
    working_dir: /var/www/app
    restart: always
    ports:
      - 9080:80
    volumes:
      - ../:/var/www/app

  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 9306:3306
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
